version: "3.8"

services:
  react-app:
    container_name: react-container
    build:
      context: .  # Build context is current directory
      dockerfile: Dockerfile  # Dockerfile in this directory
    ports:
      - "3002:3002"
    volumes:
      - .:/app
    environment:
      - NODE_ENV=development
    env_file:
      - .env
    stdin_open: true
    tty: true
